import Head from "next/head";
import { useQuery } from "@apollo/client";
import styles from "../styles/Home.module.css";
import { gql } from "@apollo/client";
import { useState } from "react";

const POSTS = gql`
  query posts($start: Int, $limit: Int) {
    posts(pagination: { start: $start, limit: $limit }) {
      data {
        id
        attributes {
          title
          text
        }
      }
      meta {
        pagination {
          total
          pageSize
          pageCount
        }
      }
    }
  }
`;

export default function Home() {
  const [start, setStart] = useState(0);
  const [limit] = useState(2);
  const model = "posts";
  const { data, fetchMore } = useQuery(POSTS, {
    variables: { start: 0, limit: limit },
  });
  const total = data?.posts?.meta?.pagination?.total;

  const handleMore = () => {
    const nextStart = start + limit;
    setStart(nextStart);
    fetchMore({
      variables: {
        start: nextStart,
        limit: limit,
      },
      updateQuery: (prevResult, { fetchMoreResult }) => {
        if (!fetchMoreResult) {
          return prevResult;
        }
        const prevData = prevResult[model].data;
        const moreData = fetchMoreResult[model].data;

        fetchMoreResult[model].data = [...prevData, ...moreData];
        return { ...fetchMoreResult };
      },
    });
  };

  // console.log(data, "data");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to this playground</h1>
        <ul>
          {data?.posts?.data?.map((post, index) => {
            return <li key={index}>{post?.attributes?.title}</li>;
          })}
        </ul>
        <button
          type="button"
          disabled={start + limit >= total}
          onClick={() => handleMore()}
        >
          More
        </button>
      </main>
    </div>
  );
}
